version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - Procfile
    - target/log4j2-project.jar
    - .ebextensions/*
    - .ebextensions/scripts/*
    - .ebextensions/scripts/*
    - .ebextensions/datadog/*    
    - .ebextensions/datadog/hooks/*